disabled_rules:
  - line_length
  - nesting
  - trailing_comma
included:
  - Client/Client/Sources
  - Presentation/Sources
type_name:
  excluded:
    - ID
    - iCloudClient
identifier_name:
  excluded:
    - id
