version: 2.1

commands:
  bootstrap:
    description: Bootstrap the project
    steps:
      - run: brew install -q gpg
      - run: make bootstrap

jobs:
  test:
    macos:
      xcode: 16.4.0
    steps:
      - checkout
      - bootstrap
      - run: make unit-test

workflows:
  version: 2
  run_tests:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
  run_tests_regularly:
    triggers:
      - schedule:
          cron: "0 9 * * 1,3"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
