version: 2.1

commands:
  bootstrap:
    description: Bootstrap the project
    steps:
      - run: brew install -q gpg
      - run: make bootstrap

jobs:
  test:
    macos:
      xcode: 16.4.0
    resource_class: m2pro.large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-spm-dependencies-{{ checksum "Bookshelf.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}-{{ checksum "Core/Package.resolved" }}-{{ checksum "Infrastructure/Package.resolved" }}-{{ checksum "Presentation/Package.resolved" }}
            - v1-spm-dependencies-{{ checksum "Bookshelf.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}
            - v1-spm-dependencies-
      - bootstrap
      - run: make unit-test
      - save_cache:
          key: v1-spm-dependencies-{{ checksum "Bookshelf.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}-{{ checksum "Core/Package.resolved" }}-{{ checksum "Infrastructure/Package.resolved" }}-{{ checksum "Presentation/Package.resolved" }}
          paths:
            - ~/Library/Developer/Xcode/DerivedData
            - ~/Library/Caches/org.swift.swiftpm
            - ~/.cache/org.swift.swiftpm
          when: always
      - store_artifacts:
          path: Presentation/Tests/PresentationTests/__Snapshots__
          destination: snapshot-test-images
          when: always

workflows:
  version: 2
  run_tests:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
  run_tests_regularly:
    triggers:
      - schedule:
          cron: "0 9 * * 1,3"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
