name: Run renovate tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - renovate.json
      - renovate.json5
      - .github/workflows/run_renovate_tests.yml

jobs:
  dry-run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: 20.17
      - name: Install Renovate CLI
        run: npm install -g renovate
      - name: Dry run
        run: |
          renovate '${{ github.repository }}' --dry-run=full
        env:
          LOG_LEVEL: debug
          RENOVATE_BASE_BRANCHES: ${{ github.sha }}
          RENOVATE_GIT_AUTHOR: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
          RENOVATE_TOKEN: ${{ github.token }}
          RENOVATE_USERNAME: renovate[bot]
